[package]
name = "game_udp"
version = "0.1.1"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
time = "*"
byteorder = "*"
itertools = "*"

[dependencies.tap]
git = "https://github.com/acmcarther/rust_tap"
